name: Testing

on:
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn clean test --file pom.xml
